### PR TITLE
Failing when port is specified with labels

### LINKED ISSUE #522: kompose.service.type label not working as expected
According to the documentation ( [User Guide - labels](https://github.com/kubernetes-incubator/kompose/blob/master/docs/user-guide.md#labels) ) I should be able to specify the label kompose.service.type: NodePort in docker-compose.yml. However it is not behaving as expected. My understanding is the services should be configured as described here https://kubernetes.io/docs/user-guide/services/#type-nodeport

docker-compose.yml

    version: "2"
    services:
      webapiapplication:
        image: webapiapplication
        labels:
          kompose.service.type: NodePort

Powershell command and output

    PS C:\agents\windows_01\_work\1\a> kompose -f .\docker-compose.yml convert
    INFO[0000] file "webapiapplication-service.yaml" created
    INFO[0000] file "webapiapplication-deployment.yaml" created

webapiapplication-service.yaml

    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.service.type: NodePort
      creationTimestamp: null
      labels:
        service: webapiapplication
      name: webapiapplication
    spec:
      clusterIP: None
      ports:
      - name: headless
        port: 55555
        targetPort: 0
      selector:
        service: webapiapplication
    status:
      loadBalancer: {}

webapiapplication-deployment.yaml

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      annotations:
        kompose.service.type: NodePort
      creationTimestamp: null
      name: webapiapplication
    spec:
      replicas: 1
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
          labels:
            service: webapiapplication
        spec:
          containers:
          - image: webapiapplication
            name: webapiapplication
            resources: {}
          restartPolicy: Always
    status: {}

### PR DESCRIPTION
**Pull request by surajnarwade**
Resolves #522
Kompose will give FATAL error if labels are given but ports are not defined

### CODE REVIEW

File: pkg/loader/compose/compose.go [hunk 1]
```diff
@@ -358,6 +358,12 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		if len(serviceConfig.Port) == 0 {
+			if composeServiceConfig.Labels["kompose.service.type"] == "NodePort" || composeServiceConfig.Labels["kompose.service.type"] == "LoadBalancer" {
```
Comment (cdrage) [inline pkg/loader/compose/compose.go]: Why are there nested if's? 

Shouldn't it be: `if len(serviceConfig.Port) == 0 &&  composeServiceConfig.Labels["kompose.service.type"] == "NodePort" || composeServiceConfig.Labels["kompose.service.type"] == "LoadBalancer"`

Comment (surajnarwade) [inline pkg/loader/compose/compose.go]: done

File: pkg/loader/compose/compose.go [hunk 2]
```diff
@@ -358,6 +358,11 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		if len(serviceConfig.Port) == 0 && composeServiceConfig.Labels["kompose.service.type"] == "NodePort" || composeServiceConfig.Labels["kompose.service.type"] == "LoadBalancer" {
+			log.Fatal("Failed to proceed as Nodeport or loadbalancer is defined without ports")
```
Comment (cdrage) [inline pkg/loader/compose/compose.go]: Was just thinking again (sorry for asking for another change) that this could be better:
```go
log.Fatal("%s defined with no ports present. Issues may occur when bringing up artifacts.", composeServiceConfig.Labels["kompose.service.type"])
```

And also change this log to warning instead? What do you think @kadel ?

Comment (surajnarwade) [inline pkg/loader/compose/compose.go]: log message is okay but giving warning instead of FATAL is of no use

Comment (cdrage) [inline pkg/loader/compose/compose.go]: @surajnarwade I think it should still convert.. Let's wait for @kadel 's opinion :+1:

Comment (surajssd) [inline pkg/loader/compose/compose.go]: I think @kadel made it clear that we should fail here https://github.com/kubernetes-incubator/kompose/issues/522#issuecomment-297451523

>yes, that makes sense, we should fail, as it doesn't make sense to use NodePort or LoadBalancer without port defined.

File: pkg/loader/compose/compose.go [hunk 3]
```diff
@@ -358,6 +358,11 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
...
+
```
Comment (surajssd) [inline pkg/loader/compose/compose.go]: nit: remove blank line

File: pkg/loader/compose/compose.go (hunk 2 above)
Comment (surajssd) [inline pkg/loader/compose/compose.go]: Please update the messge though!

**Comment by surajnarwade** [comment]
cc @kadel @cdrage

**Comment by surajssd** [comment]
@surajnarwade tests and docs update

File: pkg/loader/compose/compose.go [hunk 4]
```diff
@@ -358,6 +358,10 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		if len(serviceConfig.Port) == 0 && composeServiceConfig.Labels["kompose.service.type"] == "NodePort" || composeServiceConfig.Labels["kompose.service.type"] == "LoadBalancer" {
+			log.Fatalf("%s defined with no ports present. Issues may occur when bringing up artifacts.", composeServiceConfig.Labels["kompose.service.type"])
```
Comment (surajssd) [inline pkg/loader/compose/compose.go]: Also this one does not tell which docker-compose service has that label and no port defined together?

File: pkg/loader/compose/compose.go [hunk 5]
```diff
@@ -358,6 +358,10 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		if len(serviceConfig.Port) == 0 && composeServiceConfig.Labels["kompose.service.type"] == "NodePort" || composeServiceConfig.Labels["kompose.service.type"] == "LoadBalancer" {
+			log.Fatalf("In %s service, %s defined with no ports present. Issues may occur when bringing up artifacts.", name, composeServiceConfig.Labels["kompose.service.type"])
```
Comment (cdrage) [inline pkg/loader/compose/compose.go]: `In %s service` isn't grammatically correct.

My previous comment may work a bit better:
```
log.Fatal("%s defined in service %s with no ports present. Issues may occur when bringing up artifacts.", composeServiceConfig.Labels["kompose.service.type"], name)
```

**Comment by surajnarwade** [comment]
@cdrage @surajssd needs review

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by surajssd** [comment]
@surajnarwade tests and docs update

**Comment by gitlawr** [comment]
Would it be better if it return error here and leave the Fatalf() work to upper layer?
 I'm investigating https://github.com/kubernetes-incubator/kompose/issues/464 and I think logrus.Fatalf(...) may be a broker because it finally invokes os.Exit()
Anyway, returning an error consists with other parts of the codes:
https://github.com/surajnarwade/kompose/blob/8198246bd8363642800941be75a2b9bf414ee9b5/pkg/loader/compose/compose.go#L352

**Comment by surajnarwade** [comment]
@gitlawr , `return error here`, I didn't get you

**Comment by gitlawr** [comment]
@surajnarwade 
I mean 
```
return kobject.KomposeObject{}, errors.New("xxx defined in service xxx with no ports present. Issues may occur when bringing up artifacts.")
```
instead of
```
log.Fatalf(...)
```

File: pkg/loader/compose/compose.go [hunk 6]
```diff
@@ -359,6 +359,10 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		err = checkLabelsPorts(len(serviceConfig.Port), composeServiceConfig.Labels["kompose.service.type"], name)
+		if err != nil {
+			log.Fatal(err)
```
Comment (containscafeine) [inline pkg/loader/compose/compose.go]: Let's not use `log.Fatal`, instead wrap the error and pass it up the call stack. Use `errors.Wrap`

File: pkg/loader/compose/compose.go [hunk 7]
```diff
@@ -398,3 +402,10 @@ func handleServiceType(ServiceType string) (string, error) {
 func normalizeServiceNames(svcName string) string {
 	return strings.Replace(svcName, "_", "-", -1)
 }
+
+func checkLabelsPorts(noOfPort int, labels string, svcName string) error {
+	if noOfPort == 0 && labels == "NodePort" || labels == "LoadBalancer" {
+		return errors.Errorf("%s defined in service %s with no ports present. Issues may occur when bringing up artifacts.", labels, svcName)
```
Comment (containscafeine) [inline pkg/loader/compose/compose.go]: Let's wrap it using `errors.Wrap` to maintain consistency throughout the code.

Comment (containscafeine) [inline pkg/loader/compose/compose.go]: @surajnarwade if there is nothing to wrap, use `errors.New()`

Comment (surajnarwade) [inline pkg/loader/compose/compose.go]: @containscafeine , I have variable in my error message. so I used `errors.Errorf()` instead of `errors.New()`

Comment (containscafeine) [inline pkg/loader/compose/compose.go]: Gotcha

**Comment by surajnarwade** [comment]
@surajssd , needs review on this

**Comment by surajssd** [comment]
@surajnarwade bear with me, also please add functional tests! so when I meant tests == (unit tests and functional tests)

File: pkg/loader/compose/compose.go [hunk 8]
```diff
@@ -363,6 +363,10 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
 			}
 		}
 
+		err1 := checkLabelsPorts(len(serviceConfig.Port), composeServiceConfig.Labels["kompose.service.type"], name)
```
Comment (cdrage) [inline pkg/loader/compose/compose.go]: err1? that's not a good name for a variable. Please use `err`.

File: pkg/loader/compose/compose.go [hunk 9]
```diff
@@ -363,6 +363,10 @@ func (c *Compose) LoadFile(files []string) (kobject.KomposeObject, error) {
...
+		if err1 != nil {
+			return kobject.KomposeObject{}, errors.Wrap(err, err1.Error())
```
Comment (cdrage) [inline pkg/loader/compose/compose.go]: what's going on here? for errors.Wrap it should be `errors.Wrap(err, "Your error message here") or something along the lines.

**Comment by surajnarwade** [comment]
@cdrage , @surajssd I have updated PR with changes and added tests as well

File: pkg/loader/compose/compose.go (hunk 7 above)
Comment (kadel) [inline pkg/loader/compose/compose.go]: Let's change message a bit. It is not possible to create Headless service with type NodePort or LoadBalancer.
The Message should be more definite.
For example something in those lines:
"kompose.service.type can't be set if service doesn't expose any ports."

Comment (surajnarwade) [inline pkg/loader/compose/compose.go]: added message

**Comment by surajnarwade** [comment]
@kadel @surajssd @containscafeine can you please test now

File: docs/user-guide.md [hunk 10]
```diff
@@ -401,3 +401,7 @@ If the Docker Compose file has a volume specified for a service, the Deployment
 If the Docker Compose file has service name with `_` in it (eg.`web_service`), then it will be replaced by `-` and the service name will be renamed accordingly (eg.`web-service`). Kompose does this because "Kubernetes" doesn't allow `_` in object name.
 
 Please note that changing service name might break some `docker-compose` files.
+
+#### Warning about Labels
+
+`kompose.service.type` label should be defined with `ports` only, otherwise `kompose` will fail.
```
Comment (cdrage) [inline docs/user-guide.md]: This should be added under the `labels` section, not at the end of the user-guide file, otherwise, PR LGTM.

**Comment by surajnarwade** [comment]
@cdrage review please :)

File: docs/user-guide.md [hunk 11]
```diff
@@ -401,3 +402,5 @@ If the Docker Compose file has a volume specified for a service, the Deployment
 If the Docker Compose file has service name with `_` in it (eg.`web_service`), then it will be replaced by `-` and the service name will be renamed accordingly (eg.`web-service`). Kompose does this because "Kubernetes" doesn't allow `_` in object name.
 
 Please note that changing service name might break some `docker-compose` files.
+
+
```
Comment (cdrage) [inline docs/user-guide.md]: Remove extra newlines, update PR, then go-ahead and merge!

**Comment by surajnarwade** [comment]
All green now, @cdrage @surajssd
